name: navigation_data
publish_to: "none"

environment:
  sdk: ">=2.14.0<3.0.0"
  flutter: ">=1.17.0"

dependencies:
  aviation_entities:
    path: ../aviation_entities
  aviation_units:
    path: ../aviation_units
  collection: ^1.15.0
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  get_it: ^7.2.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  logger: ^1.1.0
  path: ^1.8.0
  sembast: ^3.1.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  lint: ^1.8.2

flutter:
  assets:
    - packages/navigation_data/data/airports_json
    - packages/navigation_data/data/runways_json
    - packages/navigation_data/data/navaids_json
